[package]
name = "media-merger"
version = "0.1.4"
edition = "2021"
authors = ["Khenzii"]
repository = "https://github.com/Khenziii/media-merger"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffprobe = "0.3.3"
pbr = "1.1.1"
