name: Build & Add Binaries To Release
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        builds:
          - x86_64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build (${{ matrix.builds }})
        uses: ./.github/actions/build/${{ matrix.builds }
