on:
  workflow_call:
    secrets:
      TOKEN_GITHUB:
        required: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add target
        run: rustup target add x86_64-pc-windows-gnu

      - name: Build
        run: cargo build --release --target x86_64-pc-windows-gnu

      - name: Upload Binary To Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/x86_64-pc-windows-gnu/release/media-merger
          asset_name: media-merger-x86_64-pc-windows-gnu
