name: Build & Add Binaries To Release
on:
  release:
    types: [published]

jobs:
  build-x86_64-w64-mingw32:
    uses: ./.github/workflows/builds/x86_64-w64-mingw32
    secrets: inherit
  build-x86_64-unknown-linux-gnu:
    uses: ./.github/workflows/builds/x86_64-unknown-linux-gnu
    secrets: inherit